### ISSUE TITLE
誤訳：語順が逆です

### ISSUE THREAD

**Issue by snvxiv** [laravel-ja/ja-docs-8.x#1]
[ページ]
https://readouble.com/laravel/8.x/ja/eloquent-relationships.html#has-one-through
[問題のある和文]
MechanicはOwnerを通じて（through）Carへアクセスできます。
[正しいと思われる和文]
MechanicはCarを通じて（through）Ownerへアクセスできます。

**Comment by HiroKws** [comment]
ありがとうございます。ご指摘の通り、修正しました。
