### ISSUE TITLE
eloquent.md タイポ「Elomequent」

### ISSUE THREAD

**Issue by datalowe** [laravel-ja/ja-docs-8.x#10]
https://github.com/laravel-ja/ja-docs-8.x/blob/master/translation-ja/eloquent.md#%E3%82%B3%E3%83%B3%E3%83%9D%E3%82%B8%E3%83%83%E3%83%88%E4%B8%BB%E3%82%AD%E3%83%BC

> Elomequentは、それぞれのモデルがその主キーとして。。。

**Comment by HiroKws** [comment]
ありがとうございます。修正し、readouble.comもアップデートしました。
