### ISSUE TITLE
Eloquent解説ページの「クエリビルダ」のリンクにTypoがあるようです

### ISSUE THREAD

**Issue by takezone** [laravel-ja/ja-docs-8.x#14]
翻訳作業をいつも大変ありがとうございます。参考にさせていただいております。
以下の「Eloquentの準備」ページでtypoがあったため報告いたします。
https://readouble.com/laravel/8.x/ja/eloquent.html

「モデルの取得」「集計の取得」の項目で
「クエリビルダ」としてリンクされているページが
https://readouble.com/laravel/8.x/ja/querys.html
となっていますが、リンク切れとなっており、
https://readouble.com/laravel/8.x/ja/queries.html
が正しいようです。

4箇所見つかりますが、1箇所は「クエリ」という形でカタカナになっているようです。

どうぞご確認ください。

**Comment by HiroKws** [comment]
ありがとうございました。readme.mdでも説明してありますが、前回の原文ドキュメント大改訂に対応するためほぼ全文訳し直しとなり、作業の軽減と、用語、表現の統一を図るため、Google翻訳などの翻訳サービスを利用する方針にしました。Markdownへの対応は考慮されつつありますが、URLが書き換えられてしまうことがあります。全く異なれば気がつくのですが、単複型の変更など意味的に近い変更は人手のため見落としがちです。
現在は念の為、原文変更が起きた部分は、原文のURLを一つづつ手作業で貼り付け直していますが、それもヒューマンエラーが入り込む余地があります。
お気づきの際は、今回同様、お知らせいただけると、ありがたいです。

**Comment by takezone** [comment]
了解いたしました。これだけ大量の文章であると、確認作業も大変かとお察しいたします。
気づいた際にはまた報告させていただきます。
迅速なご対応ありがとうございます。
