### ISSUE TITLE
「Eloquentの準備」のページで、以下の「挿入/更新」の項目の文言修正案です

### ISSUE THREAD

**Issue by takezone** [laravel-ja/ja-docs-8.x#15]
「Eloquentの準備」のページで、以下の「挿入/更新」の項目にて
https://readouble.com/laravel/8.x/ja/eloquent.html#upserts

```
以下の例では、Oaklandの「出発（departure）」場所とSan Diegoの「目的地（destination）」でフライトが存在する場合
```
という表現がありますが、
```
以下の例では、Oaklandの「出発地（departure）」とSan Diegoの「目的地（destination）」でフライトが存在する場合
```
が整合性の面とで良いかと思いました。

また、日本語的な読みやすさの面からは
```
以下の例では、Oaklandが「出発地（departure）」でSan Diegoが「目的地（destination）」でフライトが存在する場合
```
が良い気もしました。

ごく小さい話で恐縮ですが、とりあえず「出発地」に関しては整合性の面で修正が必要そうです。

ご検討ください。

**Comment by HiroKws** [comment]
ありがとうございました。修正しました。
