### ISSUE TITLE
ver 8　のタイポ修正依頼

### ISSUE THREAD

**Issue by 0123takaokeita** [laravel-ja/ja-docs-8.x#19]
https://readouble.com/laravel/8.x/ja/migrations.html

カラムの修飾子となるべきところにタイポが見つかりました。
issueまで連絡くださいと書かれているのでこちらに作成します。

<img width="593" alt="スクリーンショット 2021-07-24 9 06 17" src="https://user-images.githubusercontent.com/65272471/126851501-fb4d6c9c-d1d4-4da4-bce5-0412e294068b.png">

**Comment by HiroKws** [comment]
ありがとうございました。修正しました。
