### ISSUE TITLE
「phoneメソッドはベースのEloquentモデルクラスのhasOneメソッドを結果として返す必要があります」という表現に関して変更の提案

### ISSUE THREAD

**Issue by tarohida** [laravel-ja/ja-docs-8.x#2]
いつも参照させていただいております。

https://readouble.com/laravel/8.x/ja/eloquent-relationships.html

「hasOneメソッドが返る」という書き方に少し違和感を感じました。
「hasOneメソッドを呼び出し、その結果を返り値として返す」のが正しい意味だと思いますが、メソッドそのものが返るように感じて混乱するように思うため、

例えば

```diff
- phoneメソッドはベースのEloquentモデルクラスのhasOneメソッドを結果として返す必要があります。
+ phoneメソッドはベースのEloquentモデルクラスのhasOneメソッドを呼び出し、その結果を返す必要があります。
```

のように訳すことを提案します。

これはあくまで一案ですので、全体的な整合性など考慮しつつ、実際の変更内容については @HiroKws さんの任意にご変更ください。

**Comment by HiroKws** [comment]
ありがとうございます。やや意訳しすぎているようですので、原文に忠実に訳し直します。
