### ISSUE TITLE
コレクション解説ページの「サービスプロバイダ」のリンク切れのご報告

### ISSUE THREAD

**Issue by takezone** [laravel-ja/ja-docs-8.x#20]
いつも管理お疲れ様です。
以下のコレクションに関する解説ページで
https://readouble.com/laravel/8.x/ja/collections.html

```
通常、コレクションマクロはサービスプロバイダのbootメソッドで宣言する必要があります。
```
という部分の「サービスプロバイダ」のリンクが切れており、
URLを確認したところ
providers.html が provider.html (sが無い)となっておりました。

ご確認くださいませ。

**Comment by HiroKws** [comment]
ありがとうございます。修正いたしました。

**Comment by takezone** [comment]
ご対応ありがとうございました。
