### ISSUE TITLE
[タスクスケジュール] scheduling.md の誤訳

### ISSUE THREAD

**Issue by chimayu** [laravel-ja/ja-docs-8.x#28]
初めまして、お世話になります。

/ja-docs-8.x/translation-ja/scheduling.md : L153
ウィークエンド　→　ウィークデー

原文では以下になっており、
`// Run hourly from 8 AM to 5 PM on weekdays...`
使用されているメソッドも 
`->weekdays()`
なので修正が必要かと思いました。

**Comment by HiroKws** [comment]
ありがとうございました。
