### ISSUE TITLE
[typo]  Laravel 8.x pagination.php言語ファイル

### ISSUE THREAD

**Issue by eggpan** [laravel-ja/ja-docs-8.x#41]
https://readouble.com/laravel/8.x/ja/pagination-php.html
言語ファイルの内容について、文字参照のセミコロンが抜けているようです。

`'next' => '次 &raquo',`
ではなく
`'next' => '次 &raquo;',`
が正しいと思われます。

他バージョンも同様の記述になっているようです。

**Comment by HiroKws** [comment]
ご指摘ありがとうございました。バージョン６，７，８のみ修正しました。

基本的に、これを含む言語ファイル４つは説明通り、公式ドキュメントではありません。各自で自由に変更してもらい、改変等の意見は不要なものですので、最初のタイポがそのまま継続されてきたものと思います。
最初のエラーはもともとの言語ファイルに存在していたもので、それを私が手動で変更したときに、片方のみ修正し、片方は元のまま残ってしまったものと思います。
