### ISSUE TITLE
typo: fakeレスポンスの順番

### ISSUE THREAD

**Issue by ShirasuGyoza** [laravel-ja/ja-docs-8.x#48]
https://readouble.com/laravel/8.x/ja/http-client.html#testing
fakeレスポンスの順番

内の本文中に typo を見つけましたので、こちらに起票しました。

誤： `kake`
正： `fake`

<img width="845" alt="Screen Shot 2022-01-05 at 13 44 28" src="https://user-images.githubusercontent.com/31214487/148161854-fa81b62f-6397-4ed9-ba25-5c7fce9bc8a1.png">

**Comment by HiroKws** [comment]
ありがとうございました。
