### ISSUE TITLE
typo queryes

### ISSUE THREAD

**Issue by zumikiti** [laravel-ja/ja-docs-8.x#51]
https://github.com/laravel-ja/ja-docs-8.x/blob/b76e12f343a9517c450588fc1c2f310ac82f1718/translation-ja/eloquent-relationships.md?plain=1#L1131

```diff
- リレーションではLaravel[クエリビルダ](/docs/{{version}}/queryes)メソッドのどれでも使用できるので、クエリビルダのドキュメントを調べ、使用可能な全メソッドを習んでください。
+ リレーションではLaravel[クエリビルダ](/docs/{{version}}/queries)メソッドのどれでも使用できるので、クエリビルダのドキュメントを調べ、使用可能な全メソッドを習んでください。
```

**Comment by zumikiti** [comment]
61行目もtypoあり　querys

https://github.com/laravel-ja/ja-docs-8.x/blob/b76e12f343a9517c450588fc1c2f310ac82f1718/translation-ja/eloquent-relationships.md?plain=1#L61

**Comment by HiroKws** [comment]
ありがとうございます。体調不良のため、後ほど修正いたします。
