### ISSUE TITLE
typo:Laravel Passport イントロダクション内文章中の「な」重複

### ISSUE THREAD

**Issue by Usuyuki** [laravel-ja/ja-docs-8.x#56]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/63891531/173999563-44d9bd36-f0a2-4b73-b0fc-8bb2bf0607f8.png">

[https://readouble.com/laravel/8.x/ja/passport.html](https://readouble.com/laravel/8.x/ja/passport.html)
[https://readouble.com/laravel/9.x/ja/passport.html](https://readouble.com/laravel/9.x/ja/passport.html)

タイポを見つけましたのでご報告致します。8系、9系どちらものようです。

**Comment by HiroKws** [comment]
ありがとうございました。修正しました。
