### ISSUE TITLE
タイポの報告

### ISSUE THREAD

**Issue by tarohida** [laravel-ja/ja-docs-8.x#59]
翻訳の公開ありがとうございます。助かっております。
以下のページにタイポを見つけたのでご報告します。

https://readouble.com/laravel/8.x/ja/container.html
> bindメソッドを使用して結合を登録しできます。

よろしくおねがいします。

**Comment by HiroKws** [comment]
ご報告ありがとうございます。反映いたしました。
バージョン８は、バグフィックス期間を７月で終了しております。翻訳リポジトリも本体のリポに合わせてメンテしております。気づくのが遅れ、反映が今になりましたが、メンテ終了を明記しました。
セキュリティアップデート終了も来年の１月に迫っております。経験上、バージョンアップに一つずつ対応するのは、さほど手間ではありませんが、いくつもまとめてアップするとなると、周辺ソフトの変更なども含め、手間が増えます。老婆心ながら、最新のバージョン９へのアップデートをおすすめします。
