### ISSUE TITLE
Eloquentの準備 - イベント 説明文の誤記

### ISSUE THREAD

**Issue by jammertm** [laravel-ja/ja-docs-8.x#7]
【Laravel 8.x Eloquentの準備】
https://readouble.com/laravel/8.x/ja/eloquent.html

イベントの説明文

> Eloquentモデルはいくつかのイベントをディスパッチし、モデルのライフサイクルの以下の瞬間をフックできるようにしています。：retrieved、creating、created、updating、updated、saved、saved、delete、deleted、restoreing、restored、replicating。

1. ここでsavedが2回出現しており、片方はsavingだと思われます。
2. restoreingの正しいスペルは、restoringとなっています。

> Eloquentイベントを定義してマッピングした後は、そのイベントを処理するためにイベントリスナを使用します。

3. 「イベントリスナ」のリンクが切れています。
正） https://laravel.com/docs/8.x/events#defining-listeners
※ English原文のほうも切れていた

**Comment by HiroKws** [comment]
ありがとうございます。タイポを修正しました。
リンク切れは原文が修正された時点で修正します。日本語だけの修正は管理が煩雑なため行わない方針です。（過去はやっていましたが、経験からメンテは難しいことがわかり、原文の誤りはそのままにしておき、原文への修正依頼を出していただいてます。）

**Comment by HiroKws** [comment]
リンク切れは後ほど調べておきます。

**Comment by HiroKws** [comment]
原因は原文のリンクが絶対URLで指定されているためでした。基本は/doc以下への相対URLが使われるはずなのですが、ところどころ多種なリンク形式が使われるため、readouble.comで使用している変換スクリプトが対応しきれません。一応原文に対し、相対URLへ変更する修正を出しておきます。

**Comment by HiroKws** [comment]
https://github.com/laravel/docs/pull/7023

**Comment by HiroKws** [comment]
原文にリンクを相対URLで統一するプルリクを出し、取り込まれたため、和文でも反映しました。
