### ISSUE TITLE
「インストール」の単純なタイポ

### ISSUE THREAD

**Issue by datalowe** [laravel-ja/ja-docs-8.x#8]
（和訳してくれてありがとうございます！）

installation.mdの[ここ](https://github.com/laravel-ja/ja-docs-8.x/blob/master/translation-ja/installation.md#%E5%89%8D%E9%80%B2%E3%81%99%E3%82%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF)の二つ目の段落には「上級開発者でしたら、Laravelの依存注入、単体テスト、キュー、リアルタイムイベントなどへの堅牢なツールが役立つ**でしょいう**」と書かれています。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
